<?php
/** @var \Magenest\GiftRegistry\Block\Guest\ListSearch $block */
// @codingStandardsIgnoreFile
$keyWords = $block->getListRegistry();
$link = $block->getViewFileUrl('/');
$listEvent = $block->getListEvent();
?>
<div class="gift_view">
    <div class="gift_search_wrapper">
        <h2 class="gift_h2"><?php echo __('Find a registry')?></h2>
        <div class="gift_search_container">
            <form id="gift_search_form" class="gift_search_form" method="POST">
                <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>"/>
                <div class="select-type">
                    <select id="type-selected" name="type-selected" class="list-gift" title="Select Event Type">
                        <option selected value="*"><?php echo __("All Type")?></option>
                        <?php foreach ($listEvent as $event):?>
                            <option value="<?php echo $event->getEventType()?>"><?php echo $event->getEventTitle()?></option>
                        <?php endforeach; ?>
                    </select>
                    <select id="filter-selected" name="filter-selected" class="list-gift" title="Select Filter">
                        <option id="filter-title" value="1"><?php echo __("Filter By Title")?></option>
                        <option id="filter-name" selected value="2"><?php echo __("Filter By Name")?></option>
                    </select>
                </div>
                <div id="search-name-wrapper" class="search-name-wrapper">
                    <div class="field">
                        <input id="event_fn" name="first-name" class="search_input" type="text" placeholder="First Name">
                        <label class="mage-error" id="event_fn-error" style="display: none; color:red;">
                            <?php echo __('This is a required field.')?>
                        </label>
                    </div>
                    <div class="field">
                        <input id="event_ln" name="last-name" class="search_input" type="text" placeholder="Last Name">
                        <label class="mage-error" id="event_ln-error" style="display: none; color: red;">
                            <?php echo __('This is a required field.')?>
                        </label>
                    </div>
                </div>
                <div id="search-title-wrapper" class="search-title-wrapper" hidden>
                    <div class="field">
                        <input id="title" name="title" class="search_input" type="text" placeholder="Title">
                        <label class="mage-error" id="title-error" style="display: none; color:red;">
                            <?php echo __('This is a required field.')?>
                        </label>
                    </div>
                </div>
                <div class="btn_wrapper">
                    <button type="button" id="search_registry_submit_btn"><?php echo __('Search')?></button>
                </div>
            </form>
        </div>
    </div>
    <img src="<?php echo $link.'/Magenest_GiftRegistry/images/giftview.jpg'?>">
    <table class="data-grid" id="result-table">
        <thead>
        <tr>
            <th class="data-grid-th"><span><?php echo __('Event')?></span></th>
            <th class="data-grid-th"><span><?php echo __('First Name')?></span></th>
            <th class="data-grid-th"><span><?php echo __('Last Name')?></span></th>
            <th class="data-grid-th"><span><?php echo __('Event Type')?></span></th>
            <th class="data-grid-th"><span><?php echo __('Title')?></span></th>
            <th class="data-grid-th"><span><?php echo __('Event Location')?></span></th>
            <th class="data-grid-th"><span><?php echo __('Event Time')?></span></th>
            <th class="data-grid-th"><span><?php echo __('View')?></span></th>
        </tr>
        </thead>
        <tbody id="result-search">
        <?php
        $i = 0;
        foreach($keyWords as $keyWord){
            $infors = $block->getInforEvent($keyWord['giftregistry_id']);
            if(count($infors)){
                $i++;
                ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Event')) ?>" class="col-title">
                        <?php echo $i ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('First Name')) ?>" class="col-title">
                        <?php echo $keyWord['firstname'] ?>

                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Last Name')) ?>" class="col-title">
                        <?php echo $keyWord['lastname'] ?>

                    </td>
                    <?php $infors = $block->getInforEvent($keyWord['giftregistry_id']); foreach ($infors as $infor):?>
                        <td data-th="<?php echo $block->escapeHtml(__('Event Type')) ?>" class="col-title">
                            <?php echo $infor->getData('type') ?>

                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Event Title')) ?>" class="col-title">
                            <?php echo $infor->getData('title') ?>

                        </td>

                        <td data-th="<?php echo $block->escapeHtml(__('Event Location')) ?>" class="col-title">
                            <?php echo $infor->getData('location') ?>

                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Event Time')) ?>" class="col-title">
                            <?php echo $infor->getData('date') ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col-title">
                            <a href="<?php  echo $block->getViewUrl($infor) ?>"  target="blank" class="action view">
                                <span><?php  echo __('View') ?></span>
                            </a>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php } } ?>
        <?php if($block->isFilterByName()):?>
            <?php if ($i == 0){?>
                <tr class="data-grid-tr-no-data">
                    <td class="empty-text" colspan="8"><?php echo __("We couldn't find any record(s) with '".htmlspecialchars($block->getFirstname(), ENT_QUOTES, 'UTF-8')."' - '".htmlspecialchars($block->getLastname(), ENT_QUOTES, 'UTF-8')."'!")?></td>
                </tr>
            <?php }else {?>
                <tr class="data-grid-tr-no-data">
                    <td class="empty-text" colspan="8"><?php echo __("We found ".$i." record(s) with '".htmlspecialchars($block->getFirstname(), ENT_QUOTES, 'UTF-8')."' - '".htmlspecialchars($block->getLastname(), ENT_QUOTES, 'UTF-8')."'")?></td>
                </tr>
            <?php } ?>
        <?php else :?>
            <?php if ($i == 0){?>
                <tr class="data-grid-tr-no-data">
                    <td class="empty-text" colspan="8"><?php echo __("We couldn't find any record(s) with title '".htmlspecialchars($block->getTitle(), ENT_QUOTES, 'UTF-8')."'!")?></td>
                </tr>
            <?php }else {?>
                <tr class="data-grid-tr-no-data">
                    <td class="empty-text" colspan="8"><?php echo __("We found ".$i." record(s) with title '".htmlspecialchars($block->getTitle(), ENT_QUOTES, 'UTF-8')."'!")?></td>
                </tr>
            <?php } ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        "Magento_Ui/js/modal/modal",
        'Magenest_GiftRegistry/js/owl.carousel',
        'Magenest_GiftRegistry/js/addToCart'
    ],function ($) {
        'use strict';

        $('#filter-selected').on('change', function (e) {
            var optionSelected = $("option:selected", this);
            if(this.value == 1) {
                $("#search-name-wrapper").hide();
                $("#search-title-wrapper").show();
            }else {
                $("#search-name-wrapper").show();
                $("#search-title-wrapper").hide();
            }
        });
        $('#search_registry_submit_btn').click(function () {
            var fname = $("#event_fn").val();
            var lname = $("#event_ln").val();
            var title = $("#title").val();
            var filter = $("#filter-selected").val();
            var type = $("#type-selected").val();
            var form_key = $("#form_key").val();
            if (filter == 2) {
                if (fname.trim().length == 0 || lname.trim().length == 0) {
                    if (fname.trim().length == 0) {
                        $('#event_fn-error').show();
                        $('#event_fn').css('border', 'solid 1px red');
                    } else {
                        $('#event_fn-error').hide();
                        $('#event_fn').css('border', '');
                    }
                    if (lname.trim().length == 0) {
                        $('#event_ln-error').show();
                        $('#event_ln').css('border', 'solid 1px red');
                    } else {
                        $('#event_ln-error').hide();
                        $('#event_ln').css('border', '');
                    }
                } else {
                    $('#event_fn-error').hide();
                    $('#event_ln-error').hide();
                    $('#event_fn').css('border', '');
                    $('#event_ln').css('border', '');
                    $.ajax({
                        type: "POST",
                        url: "<?php echo $block->getSearchUrl()?>?isAjax=true",
                        data: {
                            firstName: fname,
                            lastName: lname,
                            type: type,
                            filter_selected: filter,
                            form_key: form_key
                        },
                        showLoader: true
                    }).done(function (response) {
                        var count = response.length;
                        if (count > 0) {
                            $('#result-search').empty();
                            for (var x = 0; x < count; x++) {
                                var row = "<tr>";
                                row += "<td class='col-title' >"+(x*1+1)+"</td>";
                                row += "<td class='col-title' >"+response[x].firstname+"</td>";
                                row += "<td class='col-title' >"+response[x].lastname+"</td>";
                                row += "<td class='col-title' >"+response[x].type+"</td>";
                                row += "<td class='col-title' >"+response[x].title+"</td>";
                                row += "<td class='col-title' >"+response[x].location+"</td>";
                                row += "<td class='col-title' >"+response[x].date+"</td>";
                                row += "<td class='col-title' ><a href='"+response[x].url+"' class='action view'><span><?php echo __('View')?></span></a></td>";
                                row += "</tr>";
                                $('#result-search').append(row);
                            }
                            var row = "<tr class='data-grid-tr-no-data'>";
                            row += "<td class='empty-text' colspan='8'>We found "+x+" record(s) with '"+fname+"' - '"+lname+"' </td>";
                            row += "</tr>";
                            $('#result-search').append(row);
                        } else {
                            $('#result-search').empty();
                            var row = "<tr class='data-grid-tr-no-data'>";
                            row += "<td class='empty-text' colspan='8'><?php echo __('We couldn\'t find any record(s) with ')?>'"+fname+"' - '"+lname+"'</td>";
                            row += "</tr>";
                            $('#result-search').append(row);
                        }
                    });
                }
            } else {
                if(title.trim().length == 0) {
                    $("#title-error").show();
                    $("#title").css('border', 'solid 1px red');
                } else {
                    $("#title-error").hide();
                    $('#title').css('border', '');
                    $.ajax({
                        type: "POST",
                        url: "<?php echo $block->getSearchUrl()?>?isAjax=true",
                        data: {
                            filter_selected: filter,
                            title: title,
                            type: type,
                            form_key: form_key
                        },
                        showLoader: true
                    }).done(function (response) {
                        var count = response.length;
                        if (count > 0) {
                            $('#result-search').empty();
                            for (var x = 0; x < count; x++) {
                                var row = "<tr>";
                                row += "<td class='col-title' >"+(x*1+1)+"</td>";
                                row += "<td class='col-title' >"+response[x].firstname+"</td>";
                                row += "<td class='col-title' >"+response[x].lastname+"</td>";
                                row += "<td class='col-title' >"+response[x].type+"</td>";
                                row += "<td class='col-title' >"+response[x].title+"</td>";
                                row += "<td class='col-title' >"+response[x].location+"</td>";
                                row += "<td class='col-title' >"+response[x].date+"</td>";
                                row += "<td class='col-title' ><a href='"+response[x].url+"' class='action view'><span><?php echo __('View')?></span></a></td>";
                                row += "</tr>";
                                $('#result-search').append(row);
                            }
                            var row = "<tr class='data-grid-tr-no-data'>";
                            row += "<td class='empty-text' colspan='8'>We found "+x+" record(s) with title '"+title+"' </td>";
                            row += "</tr>";
                            $('#result-search').append(row);
                        } else {
                            $('#result-search').empty();
                            var row = "<tr class='data-grid-tr-no-data'>";
                            row += "<td class='empty-text' colspan='8'><?php echo __("We couldn\'t find any record(s) with title ")?>'"+title+"'</td>";
                            row += "</tr>";
                            $('#result-search').append(row);
                        }
                    });
                }
            }
        });
    });
</script>