<?php /** @var Magento\Catalog\Block\Product\View $block */
// @codingStandardsIgnoreFile
?>

<?php
$actionUrl = $block->getUrl(
    'giftregistrys/index/checkproductsdetail',
    ['productId' => $block->getProduct()->getId()]);
?>
    <div class="add-to-gift-registry" data-role="add-to-links">
        <a href="#"
           style="text-decoration: none"
           data-product-id = "<?=$block->getProduct()->getId()?>"
           id="add-gift-link"
           data-action="add-gift-registry"
           data-product-url="<?php echo $block->getProduct()->getProductUrl() ?>"
           title="<?php echo $block->escapeHtml(__('Add to gift registry')); ?>"
           role="button">
            <i class="fa fa-gift" aria-hidden="true" style="font-size:20px"></i>
            <span><?php /* @escapeNotVerified */ echo __('Add to Gift registry') ?></span>
        </a>
    </div>
<div id="giftregistry-table" class="giftregistry-table" data-role="giftregistry-table" hidden>
    <select id="list-gift" class="list-gift">
    </select>
    <button id="add-gift-button" type="button" class="add-gift-button"><?= __('Add')?></button>
</div>
<script type="text/javascript">
    require([
        "jquery",
        "ko",
        'mage/url',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        "domReady!"
    ], function($,ko,urlbuild, domReady){
        var table = $("#giftregistry-table");
        table.hide();
        $(".add-to-gift-registry").on('click', function () {
            jQuery('div[class="page messages"]').empty();
            form = $('#product_addtocart_form');
            form.validate();
            if(form.valid()){
                $.ajax({
                    showLoader: true,
                    url: '<?=$actionUrl?>',
                    data: {
                        'type' : true
                    },
                    type: "POST",
                    dataType: 'json'
                }).done(function (response) {
                    if(response.messageType){
                        var message = $('<div class="message-error message error" ><div>'+response.messageType+'</div></div>');
                        jQuery('div[class="page messages"]').append(message);
                    }else{
                        if(response.showGift){
                            var dataGift = response.data;
                            console.log(dataGift);
                            var urlManage = response.urlManage;
                            dataGift.forEach(function (item, index) {
                                $('.list-gift').append("<option value="+item['gift_id']+" type="+item['type']+">Add to your "+item['type']+"</option>")
                            });
                            table.show();
                        } else{
                            var tmp_postData = $('#product_addtocart_form').serialize();
                            var tmp_action = response.urlAdd;
                            var loader = jQuery('body');
                            loader.loader('show');
                            var tmp_posting = $.post(tmp_action, tmp_postData).done(function (data) {
                                window.location.href = response.urlManage;
                                loader.loader('hide');
                            });
                        }
                    }
                });
            }
        });
        $("#add-gift-button").on('click', function () {
            form = $('#product_addtocart_form');
            form.validate();
            if(form.valid()){
                var giftRegistryId = $('.list-gift').val();
                var tmp_postData = $('#product_addtocart_form').serialize();
                var type = $("#list-gift option:selected").attr('type');
                var urlManage = urlbuild.build("giftregistrys/index/manageregistry/type/"+type+"/event_id/"+giftRegistryId)
                var tmp_action = urlbuild.build("giftregistrys/index/add/product/"+"<?=$block->getProduct()->getId()?>"+"/giftregistry/"+giftRegistryId);
                var loader = jQuery('body');
                loader.loader('show');
                var tmp_posting = $.post(tmp_action, tmp_postData).done(function (data) {
                    window.location.href = urlManage;
                    loader.loader('hide');
                });
            }
        });
    });
</script>