<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php

$link = $block->getViewFileUrl('/');

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
/** @var  $helper_data \Magenest\GiftRegistry\Helper\Data */
$helper_data = $this->helper('Magenest\GiftRegistry\Helper\Data');
$haveOneRegistry = $helper_data->getHaveOneRegistry();/*Count*/
$giftId = $helper_data->getGiftId();
$checkProductsUrl = $block->getBaseUrl().'giftregistrys/index/checkproducts';
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div id="message-error-add-gift"
         style="display: none;
                color: #a94442;
                background-color: #f2dede;
                border-color: #ebccd1;
                padding-right: 35px;
                padding: 15px;
                margin-bottom: 20px;
                border: 1px solid transparent;
                border-radius: 4px;">
        <div id="popup-modal-gift">
            <span> <?php echo __('Customer have to log in and create gift registry before adding item to gift registry.') ?> </span>
        </div>
    </div>

    <div id="message-error-add-option-gift"
         style="display: none;
                color: #a94442;
                background-color: #f2dede;
                border-color: #ebccd1;
                padding-right: 35px;
                padding: 15px;
                margin-bottom: 20px;
                border: 1px solid transparent;
                border-radius: 4px;">
        <div id="popup-modal-option-gift">
            <span> <?php echo __('Customer have to log in and create gift registry before adding item to gift registry.') ?> </span>
        </div>
    </div>


    <div class="products wrapper <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */
                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */
                               echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */
                                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */
                        echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                        echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                            echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */
                                            echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                   value="<?php /* @escapeNotVerified */
                                                   echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                    echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                    echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links"
                                     class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php /* @escapeNotVerified */
                                                echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */
                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?php /* @escapeNotVerified */
                                            echo __('Add to Compare') ?></span>
                                    </a>
                                    <a href="#"
                                       product-id = "<?=$_product->getId()?>"
                                       has-options = "<?php echo ($_product->getHasOptions() ?  1 :  0) ?>"
                                       class="action addgiftregistry"
                                       data-action="add-gift-registry"
                                       data-giftid='<?php echo $giftId ?>'
                                       product-type="<?php echo $_product->getTypeId()?>"
                                       url="<?php echo $block->getUrl("giftregistrys/index/manageregistry/type/" . $helper_data->getGiftType() . "/event_id/" . $helper_data->getGiftId()) ?>"
                                       haveOneRegistry="<?php echo $haveOneRegistry ?>"
                                       product-url="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $block->escapeHtml(__('Add to gift registry')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to gift registry')); ?>"
                                       role="button"><i class="fa fa-gift" aria-hidden="true"
                                                        style="font-size:20px"></i>
                                        <span><?php /* @escapeNotVerified */
                                            echo __('Add to Gift registry') ?></span>
                                    </a>
                                </div>
                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                    echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */
                                        echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }


        </script>

    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require([
        "jquery",
    ], function ($) {
        $("a[data-action='add-gift-registry']").on('click', function () {
            var productId = $(this).attr("product-id");
            var url = $(this).attr('product-url');
            $.ajax({
                showLoader: false,
                url: '<?=$checkProductsUrl?>',
                data: {
                    'productId' : productId
                },
                type: "POST",
                dataType: 'json'
            }).done(function (response) {
                console.log(response);
                var notice = $('<div class="message-notice message notice" ><div>'+response.message+'</div></div>');
                var success = $('<div class="message-success message success" ><div>'+response.message+'</div></div>');
                switch(response.data) {
                    case 1:
                        $("#message-error-add-gift").show();
                        break;
                    case 2:
                        jQuery('div[class="page messages"]').append(notice);
                        window.location.href = url;
                        break;
                    case 3:
                        jQuery('div[class="page messages"]').append(success);
                        window.location.href = response.url;
                        break;
                    default:
                        break;
                }
            });
        });
    });
</script>
