<?php
/**
 $block->getRewardsData()  \Mirasvit\Rewards\Helper\Data  $_rewardsData
 */
?>
<div class="block block-rewards-account-summary">
    <div class="block-title">
        <strong><?=__('Points Summary') ?></strong>
    </div>

    <div>
        <?= __('You have <b>%1</b> in your account.', $this->helper('Mirasvit\Rewards\Helper\Data')->formatPoints($block->getBalancePoints())); ?>
        <?php if ($block->getDaysUntilExpiry()): ?>
           <div class="expiry-points"><?= __('Your points balance will expire in %1 days.', $block->getDaysUntilExpiry()); ?></div>
        <?php endif; ?>
    </div>
    <a href="<?= $block->getUrl('rewards/account'); ?>">
        <?= __('Visit My Reward Points Section') ?>
    </a>
</div>
