<?php /** @var \Mirasvit\Rewards\Block\Notification\Component $block */ ?>
<div class="rewards-notifications" data-bind="scope: 'rewardsNotifications'">
    <!-- ko if: messages() && messages().length > 0 -->
        <div data-bind="html: messages()"></div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "rewardsNotifications": {
                        "component": "Mirasvit_Rewards/js/view/rewards-notifications",
                        "url": "<?= $block->getNotificationUrl() ?>"
                    }
                }
            }
        }
    }
</script>
