<div class="buttons-googleplus-one">
    <script type="text/javascript">
        var rewardsOneUrl = '<?= $block->getOneUrl(); ?>';
    </script>
    <a class="plus-googleplus-one" href="https://plus.google.com/share?url=<?php echo $block->getOneUrl(); ?>"
       onclick="javascript:window.open(this.href, '',
            'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">
        <img src="https://www.gstatic.com/images/icons/gplus-32.png" alt="Share on Google+"/>
    </a>
    <?php if ($block->getEstimatedEarnPoints() > 0): ?>
        <?php if ($block->isAuthorized() && !$block->isLiked()): ?>
            <div id="googleplus-message">
                <?= __('Plus this page and earn %1',  $this->helper('Mirasvit\Rewards\Helper\Data')->formatPoints($block->getEstimatedEarnPoints())); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>