<script type="text/javascript">
/*global define */
deps.push('jquery');
require(deps, function () {
    'use strict';

    var checkBoxes = [];
    var warning = false;
    var $ = jQuery;

    <?php $myBlock = $block->getLayout()->getBlock('customerGrid'); ?>
    <?php if (is_object($myBlock) && $myBlock->getJsObjectName()): ?>
        if (checkBoxes.length > 0) {
            warning = true;
        }
        $('#in_transaction_user').val(checkBoxes.join(','));

        function registerUserRole(grid, element, checked) {
            if (checked) {
                checkBoxes[element.value] = element.value + '=' + checked;
            } else {
                checkBoxes[element.value] = null;
            }
            $('#in_transaction_user').val(getJoinedValues(checkBoxes));
            grid.reloadParams = {'in_transaction_user[]': getKeys(checkBoxes)};
        }

        function transactionUsersRowClick(grid, event) {
            var currentElement = Event.element(event);
            var rowElement = currentElement;
            if (currentElement.tagName != 'TR') {
                rowElement = $(currentElement).parents('tr');
            }
            var checkbox = $('td input', rowElement);
            if (checkbox.length) {
                if (currentElement.tagName != 'INPUT' && currentElement.tagName != 'LABEL') {
                    checkbox[0].checked = !checkbox[0].checked;
                }
                if (!checkbox[0].checked) {
                    checkBoxes[checkbox[0].value] = null;
                }
                else {
                    checkBoxes[checkbox[0].value] = checkbox[0].value + '=' + checkbox[0].checked;
                    varienElementMethods.setHasChanges(checkbox[0]);
                }

                $('#in_transaction_user').val(getJoinedValues(checkBoxes));
                grid.reloadParams = {'in_transaction_user[]': getKeys(checkBoxes)};
            }
        }

        function transactionUsersRowInit(grid, row) {
            var checkbox = $('.checkbox', row)[0];
            if (checkbox) {
                if (checkbox.checked) {
                    checkBoxes[checkbox.value] = checkbox.value + '=' + checkbox.checked;
                } else {
                    checkBoxes[checkbox.value] = null;
                }

                $('#in_transaction_user').val(getJoinedValues(checkBoxes));
                grid.reloadParams = {'in_transaction_user[]': getKeys(checkBoxes)};
            }
        }

        function getKeys(object) {
            if (typeof object != 'object') { throw new TypeError(); }
            var results = [];
            for (var property in object) {
                if (object.hasOwnProperty(property)) {
                    results.push(property);
                }
            }
            return results;
        }

        function getJoinedValues(object, separator) {
            if (typeof separator == 'undefined') {
                separator = ',';
            }
            if (typeof object != 'object') { throw new TypeError(); }
            var results = [];
            for (var property in object) {
                if (object.hasOwnProperty(property) && object[property]) {
                    results.push(object[property]);
                }
            }
            return results.join(separator);
        }

        <?php echo $myBlock->getJsObjectName() ?>.rowClickCallback = transactionUsersRowClick;
        <?php echo $myBlock->getJsObjectName() ?>.initRowCallback = transactionUsersRowInit;
        <?php echo $myBlock->getJsObjectName() ?>.checkboxCheckCallback = registerUserRole;

        <?php echo $myBlock->getJsObjectName() ?>.rows.each(function (row) {
            transactionUsersRowInit(<?php echo $myBlock->getJsObjectName() ?>, row)
        });
        $('#in_transaction_user_old').val($('#in_transaction_user').val());
    <?php endif; ?>
});
</script>
