<?php
// @codingStandardsIgnoreFile
?>
<fieldset class="fieldset">
    <h2 class="legend"><?php echo __('Baby Information')?></h2>
    <div class="field required">
        <label for="location" class="required label"><?php  echo __('Baby\'s Name') ?></label>
        <div class="input-box" style="width: 50%">
            <input type="text" data-validate="{required:true}" id="baby_name" name="baby_name" value="<?php echo $options['baby_name']?>" />
        </div>
    </div>
</fieldset>