<?php
// @codingStandardsIgnoreFile
?>
<fieldset class="fieldset">
    <h2 class="legend"><?php echo __('Christmas Information')?></h2>
    <div class="field">
        <div class="panel-heading label"><?php echo __('Add a greeting to friends and family at the top of your registry ') ?></div>
        <div class="panel-body">
            <textarea id="greeting" name="greeting" placeholder="You write row to thank my friends"><?php echo $options['greeting'] ?></textarea>
        </div>
    </div>
</fieldset>