<?php
/**
 * Created by PhpStorm.
 * User: thienmagenest
 * Date: 20/07/2017
 * Time: 13:25
 */
/**
 * @var $block \Magenest\GiftRegistry\Block\Guest\ListSearch
 */
// @codingStandardsIgnoreFile
$type = $block->getTypeEvent();
?>
<div class="gift_view">
    <img src="<?php echo $block->getViewFileUrl('/').'/Magenest_GiftRegistry/images/giftview.jpg'?>">
    <div class="result_search_type">
        <div class="result">
            <table class="data-grid" id="result-table">
                <thead>
                <tr style="border-bottom: solid 1px gainsboro;">
                    <th class="data-grid-th"><?php echo __('Stt') ?></th>
                    <th class="data-grid-th">
                        <?php if ($type == 'weddinggift') {
                            echo __("Husband's Name");
                        } elseif ($type == 'babygift') {
                            echo __("Baby's Name");
                        } else {
                            echo __("First Name");
                        }
                        ?>
                    </th class="data-grid-th">
                    <?php if ($type == 'weddinggift'): ?>
                        <th class="data-grid-th"><?php echo __('Wife\'s Name') ?></th>
                    <?php elseif ($type == 'babygift'): ?>
                    <?php else: ?>
                        <th class="data-grid-th"><?php echo __('Last Name') ?></th>
                    <?php endif; ?>
                    <th class="data-grid-th"><?php echo __('Title') ?></th>
                    <th class="data-grid-th"><?php echo __('Date') ?></th>
                    <th class="data-grid-th"><?php echo __('Action') ?></th>
                </tr>

                </thead>
                <tbody id="result-search">
                <?php $i = 0; ?>
                <?php if ($type == 'weddinggift'): ?>
                    <?php $data = $block->searchTypeWedding($type);
                    foreach ($data as $gift): ?>
                        <?php $i++;
                        $option = json_decode($gift['gift_options']); ?>
                        <tr>
                            <a target="_blank" href="<?php echo $block->getViewUrl($gift) ?>">
                                <td class="col-title"><?php echo $i ?></td>
                                <td class="col-title"><?php echo $option->{'husband_name'} ?></td>
                                <td class="col-title"><?php echo $option->{'wife_name'} ?></td>
                                <td class="col-title"><?php echo $gift['title'] ?></td>
                                <td class="col-title"><?php echo $gift['date'] ?></td>
                                <td class="col-title"><a target="_blank"
                                                         href="<?php echo $block->getViewUrl($gift) ?>"><?php echo __('View') ?></a></td>
                            </a>
                        </tr>
                    <?php endforeach; ?>
                <?php elseif ($type == 'babygift'): ?>
                    <?php $data = $block->searchTypeBaby($type);
                    foreach ($data as $gift): ?>
                        <?php $i++;
                        $option = json_decode($gift['gift_options']); ?>
                        <tr>
                            <a target="_blank" href="<?php echo $block->getViewUrl($gift) ?>">
                                <td class="col-title"><?php echo $i ?></td>
                                <td class="col-title"><?php echo $option->{'baby_name'} ?></td>
                                <td class="col-title"><?php echo $gift['title'] ?></td>
                                <td class="col-title"><?php echo $gift['date'] ?></td>
                                <td class="col-title"><a target="_blank"
                                                         href="<?php echo $block->getViewUrl($gift) ?>"><?php echo __('View') ?></a></td>
                            </a>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php $list = $block->getListRegistry(); ?>
                    <?php foreach ($list as $registran): ?>
                        <?php $gift_by_type = $block->getInforEventByType($registran['giftregistry_id'], $type); ?>
                        <?php if ($gift_by_type): ?>
                            <?php $i++; ?>
                            <tr>
                                <a target="_blank" href="<?php echo $block->getViewUrl($gift_by_type) ?>">
                                    <td class="col-title"><?php echo $i ?></td>
                                    <td class="col-title"><?php echo $registran['firstname'] ?></td>
                                    <td class="col-title"><?php echo $registran['lastname'] ?></td>
                                    <td class="col-title"><?php echo $gift_by_type['title'] ?></td>
                                    <td class="col-title"><?php echo $registran['created_time'] ?></td>
                                    <td class="col-title"><a target="_blank"
                                                             href="<?php echo $block->getViewUrl($gift_by_type) ?>"><?php echo __('View') ?></a>
                                    </td>
                                </a>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <tr class="data-grid-tr-no-data">
                    <td class="empty-text" colspan="8" id="message_result"></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    require([
        'jquery',
    ], function ($) {
        'use strict';
        var count = '<?php echo $i;?>';
        var type = '<?php echo $type;?>';
        var husband = '<?php echo $block->getHusbandName() ?>';
        var wife = '<?php echo $block->getWifeName() ?>';
        if (count > 0) {
            if (type == 'babygift') {
                $('#message_result').append('We found ' + count + ' record(s) with Baby Name: \'<?php echo htmlspecialchars($block->getBabyName(), ENT_QUOTES, 'UTF-8'); ?>\'  ');
            } else {
                if (type == 'weddinggift') {
                    if (husband != '' && wife != '') {
                        $('#message_result').append('We found ' + count + ' record(s) with Husband\'s Name: \' <?php echo htmlspecialchars($block->getHusbandName(), ENT_QUOTES, 'UTF-8'); ?> \'' + ' and Wife\'s Name: \'<?php echo htmlspecialchars($block->getWifeName(), ENT_QUOTES, 'UTF-8'); ?>\' .');
                    } else {
                        if (husband == '') {
                            $('#message_result').append('We found ' + count + ' record(s) with Wife\'s Name: \'<?php echo htmlspecialchars($block->getWifeName(), ENT_QUOTES, 'UTF-8'); ?>\' .');
                        } else {
                            $('#message_result').append('We found ' + count + ' record(s) with Husband\'s Name: \' <?php echo htmlspecialchars($block->getHusbandName(), ENT_QUOTES, 'UTF-8'); ?> \'.');
                        }
                    }
                } else {
                    $('#message_result').append('We found ' + count + ' record(s) with First Name: <?php echo htmlspecialchars($block->getFirstName(), ENT_QUOTES, 'UTF-8');?>' + ' and Last Name: <?php echo htmlspecialchars($block->getLastName(), ENT_QUOTES, 'UTF-8'); ?>');
                }
            }
        } else {
            if (type == 'babygift') {
                $('#message_result').append('We couldn\'t found any record with Baby Name: \'<?php echo htmlspecialchars($block->getBabyName(), ENT_QUOTES, 'UTF-8'); ?>\'  ');
            } else {
                if (type == 'weddinggift') {
                    if (husband != '' && wife != '') {
                        $('#message_result').append('We couldn\'t found any recordwith Husband\'s Name: \' <?php echo htmlspecialchars($block->getHusbandName(), ENT_QUOTES, 'UTF-8'); ?> \'' + ' and Wife\'s Name: \'<?php echo htmlspecialchars($block->getWifeName(), ENT_QUOTES, 'UTF-8'); ?>\' .');
                    } else {
                        if (husband == '') {
                            $('#message_result').append('We couldn\'t found any record with Wife\'s Name: \'<?php echo htmlspecialchars($block->getWifeName(), ENT_QUOTES, 'UTF-8'); ?>\' .');
                        } else {
                            $('#message_result').append('We couldn\'t found any record with Husband\'s Name: \' <?php echo htmlspecialchars($block->getHusbandName(), ENT_QUOTES, 'UTF-8'); ?> \'.');
                        }
                    }
                } else {
                    $('#message_result').append('We couldn\'t found any record with First Name: <?php echo htmlspecialchars($block->getFirstName(), ENT_QUOTES, 'UTF-8');?>' + ' and Last Name: <?php echo htmlspecialchars($block->getLastName(), ENT_QUOTES, 'UTF-8'); ?>');
                }
            }
        }
    });
</script>