<?php
/** @var Mirasvit\Rewards\Block\Checkout\Cart\Tooltip $block */
?>
<?php
$points = $block->getEarnPoints();
?>
<?php if ($points): ?>
<div class="reward-message">
    <div class="messages">
        <div class="success message">
            <span>
                <?= __('Checkout now and earn <b>%1</b> for this order.', $points) ?>
            </span>
            <?php if ($block->hasGuestNote()):?>
                <p class="limit">
                    <?= __('Applies only to registered customers, may vary when logged in.')?>
                </p>
            <?php endif;?>
		</div>
    </div>
</div>
<?php endif;?>