<?php
/**
 $block->getRewardsData()  \Mirasvit\Rewards\Helper\Data  $_rewardsData
 */
?>
<?php
if (!$block->getMaxPointsNumberToSpent()) {
    return;
}
/** @var \Mirasvit\Rewards\Helper\Data $helper */
$helper = $this->helper('Mirasvit\Rewards\Helper\Data');
?>
<li>
<div class="page-title">
<h1><?= __('Use %1', $helper->getPointsName()) ?></h1>
</div>
<div class="onestepcheckout-rewards">
    <div class="discount">
        <div class="discount-form">
            <label for="points_amount"><?= __('You have <b>%1</b> available.', $this->helper('Mirasvit\Rewards\Helper\Data')->formatPoints($block->getBalancePoints())) ?><br>

            <?= __('Enter amount of points to spend:'); ?>
            </label>
            <div class="input-box">
                <input class="input-text" id="points_amount" name="points_amount" value="<?= $block->getPointsAmount() ? $block->htmlEscape($block->getPointsAmount()) : '' ?>" />
            </div>
            <div class="input-box">
                <input type='checkbox' id="points_all" name="points_all"
                <?= $block->getPointsAmount() == $block->getMaxPointsNumberToSpent() ? 'checked' : ''?> />
                <label for="points_all"><?= __('Use maximum %1', $this->helper('Mirasvit\Rewards\Helper\Data')->formatPoints($block->getMaxPointsNumberToSpent()))?></label>
            </div>
                <button id="onestepcheckout-rewards-add" type="button" title="<?= __('Apply Points') ?>" class="button" value="<?= __('Apply Points') ?>"><span><span><?= __('Apply Points') ?></span></span></button>
                <span id="cancel_block" <?= $block->getPointsAmount() ? '' : 'style="display:none"' ?>>
                    &nbsp; <button id="onestepcheckout-rewards-cancel" type="button" title="<?= __('Cancel Points') ?>" class="button" value="<?= __('Cancel Points') ?>"><span><span><?= __('Cancel Points') ?></span></span></button>
                </span>
        </div>
    </div>
<script type="text/javascript">
//<![CDATA[
var rewardsForm = new VarienForm('reward-points-form');

Event.observe($('points_all'), 'click', function(){
    if ($('points_amount').value == <?= $block->getMaxPointsNumberToSpent() ?>) {
        $('points_amount').value = '';
    } else {
        $('points_amount').value = <?= $block->getMaxPointsNumberToSpent() ?>;
    }
});
Event.observe($('points_amount'), 'keyup', function(){
    var val = parseInt($('points_amount').value);
    if (isNaN(val) || val < <?= $block->getMaxPointsNumberToSpent() ?>) {
        $('points_all').checked = false;
    } else {
        $('points_all').checked = true;
        $('points_amount').value = <?= $block->getMaxPointsNumberToSpent() ?>;
    }
});
//]]>
</script>

            <script>
            Event.observe(window, 'load', function() {
                $('onestepcheckout-rewards-add').observe('click', function(e)    {
                    $('points_amount').addClassName('required-entry');
                    updatePoints();
                });
                $('onestepcheckout-rewards-cancel').observe('click', function(e)    {
                    $('points_amount').removeClassName('required-entry');
                    $('points_amount').setValue('');
                    $('points_all').checked = false;
                    updatePoints();
                });
            });

            function updatePoints() {
                var points_amount = $('points_amount').getValue();
                if (points_amount > 0) {
                    $('cancel_block').show();
                } else {
                    $('cancel_block').hide();
                }

                var url = '<?= $block->getUrl('rewards/checkout/applyPointsApptanaOnestepcheckout', ['_secure' => true]) ?>';
                var parameters = {points_amount: points_amount};

                var summary = $('checkout-review-load');
                summary.update('<div class="loading-ajax">&nbsp;</div>');

                new Ajax.Request(url, {
                    method: 'post',
                    parameters: parameters,
                    onSuccess: function(transport) {
                        if(transport.status == 200) {

                            var response = transport.responseText.evalJSON();

                            if(response.success) {
                               // summary.update(response.summary);
                                checkout.reloadReviewBlock();
                            }
                            else    {
                                // summary.update(response.summary);
                                 checkout.reloadReviewBlock();
                            }
                        }
                    }
                });
            }
            </script>
        </div>
</li>